title: Junhyeok Lee
url: "https://wnsx0000.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/wnsx0000"
footer_text: "Junhyeok Lee"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
